# XyrisOS 7.4 application helper.
set(XYRIS_SDK_ROOT "${XYRIS_SDK_ROOT}" CACHE PATH "Xyris SDK installation/source root")
if(NOT XYRIS_SDK_ROOT)
  if(DEFINED ENV{XYRIS_SDK_ROOT})
    set(XYRIS_SDK_ROOT "$ENV{XYRIS_SDK_ROOT}")
  else()
    set(XYRIS_SDK_ROOT "${CMAKE_CURRENT_LIST_DIR}/../../xyris-sdk")
  endif()
endif()

if(EXISTS "${XYRIS_SDK_ROOT}/lib/cmake/XyrisSDK/XyrisSDKConfig.cmake")
  list(APPEND CMAKE_PREFIX_PATH "${XYRIS_SDK_ROOT}")
  find_package(XyrisSDK CONFIG REQUIRED)
elseif(EXISTS "${XYRIS_SDK_ROOT}/CMakeLists.txt")
  add_subdirectory("${XYRIS_SDK_ROOT}" "${CMAKE_BINARY_DIR}/xyris-sdk")
  if(NOT TARGET Xyris::SDK)
    add_library(Xyris::SDK ALIAS xyris-sdk)
  endif()
else()
  message(FATAL_ERROR "Xyris SDK not found at '${XYRIS_SDK_ROOT}'")
endif()

function(xyris_add_application target)
  cmake_parse_arguments(APP "" "LINKER_SCRIPT;OUTPUT_NAME" "SOURCES" ${ARGN})
  if(NOT APP_SOURCES)
    message(FATAL_ERROR "xyris_add_application(${target}): SOURCES is required")
  endif()
  add_executable(${target} ${APP_SOURCES})
  target_link_libraries(${target} PRIVATE Xyris::SDK)
  target_compile_options(${target} PRIVATE -ffreestanding -fno-stack-protector -fno-stack-check -fno-pic -fno-pie -mno-red-zone)
  set(_linker "${APP_LINKER_SCRIPT}")
  if(NOT _linker)
    set(_linker "${CMAKE_CURRENT_SOURCE_DIR}/user.ld")
  endif()
  target_link_options(${target} PRIVATE -nostdlib -static -Wl,-m,elf_x86_64 -Wl,-z,max-page-size=0x1000 -Wl,--gc-sections -Wl,-T,${_linker})
  if(APP_OUTPUT_NAME)
    set_target_properties(${target} PROPERTIES OUTPUT_NAME "${APP_OUTPUT_NAME}")
  endif()
endfunction()
