#ifndef XYRIS_USERSPACE_INIT_SYSTEM_SERVICE_ADAPTER_H
#define XYRIS_USERSPACE_INIT_SYSTEM_SERVICE_ADAPTER_H

#include "../services/system/system_service.h"

#endif /* XYRIS_USERSPACE_INIT_SYSTEM_SERVICE_ADAPTER_H */
