# XyrisOS 7.4 userspace application toolchain (x86_64, freestanding).
set(CMAKE_SYSTEM_NAME Generic)
set(CMAKE_SYSTEM_PROCESSOR x86_64)
set(CMAKE_TRY_COMPILE_TARGET_TYPE STATIC_LIBRARY)
find_program(XYRIS_USER_CC NAMES x86_64-elf-gcc gcc REQUIRED)
find_program(XYRIS_USER_CXX NAMES x86_64-elf-g++ g++ REQUIRED)
find_program(XYRIS_USER_OBJCOPY NAMES x86_64-elf-objcopy objcopy REQUIRED)
set(CMAKE_C_COMPILER "${XYRIS_USER_CC}")
set(CMAKE_CXX_COMPILER "${XYRIS_USER_CXX}")
set(CMAKE_OBJCOPY "${XYRIS_USER_OBJCOPY}")
set(CMAKE_C_STANDARD 23)
set(CMAKE_CXX_STANDARD 20)
set(CMAKE_C_FLAGS_INIT "-ffreestanding -fno-stack-protector -fno-stack-check -fno-pic -fno-pie -fno-lto -ffunction-sections -fdata-sections -m64 -march=x86-64 -mabi=sysv -mno-80387 -mno-mmx -mno-sse -mno-sse2 -mno-red-zone -mcmodel=small -Wall -Wextra -Werror")
set(CMAKE_CXX_FLAGS_INIT "${CMAKE_C_FLAGS_INIT} -fno-exceptions -fno-rtti")
set(CMAKE_EXE_LINKER_FLAGS_INIT "-nostdlib -static -Wl,-m,elf_x86_64 -Wl,-z,max-page-size=0x1000 -Wl,--gc-sections")
